# This is a basic workflow to help you get started with Actions

name: Publish Documentation

# Run this workflow on push to main branch or when manually request
# on Github's UI
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      # Install git, configure user details, and set up SSH key
      - name: Install and Configure git
        run: |
          mkdir -p .ssh
          echo "${{ secrets.DEPLOY_KEY_PRIVATE }}" > .ssh/id_ed25519
          chmod 0400 .ssh/id_ed25519
          git config --global user.name "Kernel DocBot"
          git config --global user.email "jhkolb@umn.edu"

      - name: Generate HTML
        run: |
          docker pull sphinxdoc/sphinx
          docker run -v `pwd`:/docs sphinxdoc/sphinx sphinx-build -b html . output
      
      # Clone existing github pages repo, move in new files, and push
      - name: Push New Docs
        run: |
          git clone git@github.com:UMN-Kernel-Study-Group/UMN-Kernel-Study-Group.github.io.git
          rm -rf UMN-Kernel-Study-Group.github.io/docs
          cp -r output UMN-Kernel-Study-Group.github.io/docs
          cd UMN-Kernel-Study-Group.github.io
          git add docs
          git push
